/**
 * Base Security Schema
 * Creates the core tables for authentication and authorization.
 * Refactored for Phase 1 (Strict Relational Schema)
 */
export const BASE_SCHEMA = [
    // Schema
    `create schema if not exists security;`,

    // Profiles table (Renamed columns)
    `create table if not exists security.profiles (
        profile_id bigint generated by default as identity primary key,
        profile_name text not null unique
    );`,

    // Users table (Renamed columns)
    `create table if not exists security.users (
        user_id bigint generated by default as identity primary key,
        username text not null unique, -- Kept for compat
        user_password text not null,
        profile_id bigint not null references security.profiles(profile_id),
        user_is_active boolean not null default true,
        user_created_at timestamptz not null default now(),
        user_updated_at timestamptz not null default now(),
        user_last_login_at timestamptz
    );`,

    // User-Profile mapping (Singular)
    `create table if not exists security.user_profile (
        user_profile_id bigint generated by default as identity primary key,
        user_id bigint not null references security.users(user_id) on delete cascade,
        profile_id bigint not null references security.profiles(profile_id) on delete cascade,
        assigned_at timestamptz not null default now(),
        constraint uq_user_profile unique (user_id, profile_id)
    );`,

    // Objects (Business Objects)
    `create table if not exists security.objects (
        object_id bigint generated by default as identity primary key,
        object_name text not null unique
    );`,

    // Methods (Renamed/Split)
    `create table if not exists security.methods (
        method_id bigint generated by default as identity primary key,
        method_name text not null
    );`,

    // Object Method Link
    `create table if not exists security.object_method (
        object_method_id bigint generated by default as identity primary key,
        object_id bigint not null references security.objects(object_id) on delete cascade,
        method_id bigint not null references security.methods(method_id) on delete cascade,
        constraint uq_object_method unique (object_id, method_id)
    );`,

    // Transactions
    `create table if not exists security.transactions (
        transaction_id bigint generated by default as identity primary key,
        transaction_number text unique,
        method_id bigint references security.methods(method_id),
        object_id bigint references security.objects(object_id),
        subsystem_id integer -- references security.subsystems(subsystem_id) (Defined elsewhere or need to define here?)
    );`,
    // Note: subsystems is defined in 50_refactor. We should probably move it here or keep separation?
    // Keeping strict separation: this file is "Base". OLD base didn't have subsystems.
    // If I add FK to subsystems here, and subsystems is created in 50_, then 01_ fails on fresh install.
    // So I will OMIT FK to subsystems here, or assume subsystems is created in 50_ and alter table there?
    // OR I should add `create table subsystems` here.
    // The previous 01_base.ts didn't have subsystems.
    // I will leave transactions creation here but without FK to subsystems if subsystems isn't here.
    // Actually, I should probably leave `transactions` creation to `50_` if it's new?
    // But `01_` had `methods` with `tx`.
    // I'll keep the `methods` (legacy-ish) structure? No, I must update to new schema.

    // Permission mapping (Renamed to profile_method)
    `create table if not exists security.profile_method (
        profile_method_id bigint generated by default as identity primary key,
        profile_id bigint not null references security.profiles(profile_id) on delete cascade,
        method_id bigint not null references security.methods(method_id) on delete cascade,
        constraint uq_profile_method unique (profile_id, method_id)
    );`,

    // Indexes
    `create index if not exists ix_user_profile_profile_id on security.user_profile(profile_id);`,
    `create index if not exists ix_methods_method_name on security.methods(method_name);`,
    `create index if not exists ix_profile_method_method_id on security.profile_method(method_id);`,
]
