/**
 * Phase 1: Security Foundation
 * Creates the security schema and core identity tables.
 * Tables are PLURAL with LONG column names (base state for naming migration).
 *
 * TODO(REVERT_NAMING): This file represents the original schema state.
 */
export const BASE_SCHEMA = [
    `CREATE SCHEMA IF NOT EXISTS security;`,

    // Profiles
    `CREATE TABLE IF NOT EXISTS security.profiles (
        profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        profile_name TEXT NOT NULL UNIQUE
    );`,

    // Users (with profile_id 1:N — migrated to N:M by 74)
    `CREATE TABLE IF NOT EXISTS security.users (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        user_password TEXT NOT NULL,
        profile_id BIGINT NOT NULL REFERENCES security.profiles(profile_id),
        user_is_active BOOLEAN NOT NULL DEFAULT TRUE,
        user_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        user_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        user_last_login_at TIMESTAMPTZ
    );`,
]
