/**
 * Phase 1: Security Access Control
 * Authorization entities: objects, methods, transactions, and permission junctions.
 * Tables are PLURAL with LONG column names (base state for naming migration).
 *
 * TODO(REVERT_NAMING): This file represents the original schema state.
 */
export const ACCESS_SCHEMA = [
    // Objects (Business Objects)
    `CREATE TABLE IF NOT EXISTS security.objects (
        object_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        object_name TEXT NOT NULL UNIQUE
    );`,

    // Methods
    `CREATE TABLE IF NOT EXISTS security.methods (
        method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        method_name TEXT NOT NULL
    );`,

    // Object-Method junction
    `CREATE TABLE IF NOT EXISTS security.object_method (
        object_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        object_id BIGINT NOT NULL REFERENCES security.objects(object_id) ON DELETE CASCADE,
        method_id BIGINT NOT NULL REFERENCES security.methods(method_id) ON DELETE CASCADE,
        CONSTRAINT uq_object_method UNIQUE (object_id, method_id)
    );`,

    // Transactions
    `CREATE TABLE IF NOT EXISTS security.transactions (
        transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        transaction_number TEXT UNIQUE,
        method_id BIGINT REFERENCES security.methods(method_id),
        object_id BIGINT REFERENCES security.objects(object_id)
    );`,

    // Profile-Method permissions
    `CREATE TABLE IF NOT EXISTS security.profile_method (
        profile_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        profile_id BIGINT NOT NULL REFERENCES security.profiles(profile_id) ON DELETE CASCADE,
        method_id BIGINT NOT NULL REFERENCES security.methods(method_id) ON DELETE CASCADE,
        CONSTRAINT uq_profile_method UNIQUE (profile_id, method_id)
    );`,

    // Indexes
    `CREATE INDEX IF NOT EXISTS ix_methods_method_name ON security.methods(method_name);`,
    `CREATE INDEX IF NOT EXISTS ix_profile_method_method_id ON security.profile_method(method_id);`,
]
