/**
 * Phase 3: Authentication Tables
 * Password resets, one-time codes, and user devices.
 * Columns use proper table prefix (base state for naming migration).
 *
 * TODO(REVERT_NAMING): This file represents the original column names.
 */
export const AUTH_SCHEMA = [
    // Password Resets
    `CREATE TABLE IF NOT EXISTS security.password_resets (
        password_reset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES security.users(user_id) ON DELETE CASCADE,
        password_reset_token_hash TEXT NOT NULL,
        password_reset_sent_to TEXT,
        password_reset_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        password_reset_expires_at TIMESTAMPTZ NOT NULL,
        password_reset_used_at TIMESTAMPTZ,
        password_reset_ip INET,
        password_reset_ua TEXT,
        password_reset_attempt_count INTEGER NOT NULL DEFAULT 0,
        password_reset_meta JSONB
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uq_password_resets_token_hash ON security.password_resets(password_reset_token_hash);`,
    `CREATE INDEX IF NOT EXISTS ix_password_resets_user_id ON security.password_resets(user_id);`,
    `CREATE INDEX IF NOT EXISTS ix_password_resets_expires_at ON security.password_resets(password_reset_expires_at);`,

    // One-Time Codes (OTP, Email Verification, etc.)
    `CREATE TABLE IF NOT EXISTS security.one_time_codes (
        one_time_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES security.users(user_id) ON DELETE CASCADE,
        one_time_code_purpose TEXT NOT NULL,
        one_time_code_hash TEXT NOT NULL,
        one_time_code_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        one_time_code_expires_at TIMESTAMPTZ NOT NULL,
        one_time_code_consumed_at TIMESTAMPTZ,
        one_time_code_attempt_count INTEGER NOT NULL DEFAULT 0,
        one_time_code_meta JSONB
    );`,
    `CREATE INDEX IF NOT EXISTS ix_one_time_codes_user_purpose ON security.one_time_codes(user_id, one_time_code_purpose, one_time_code_created_at DESC);`,
    `CREATE INDEX IF NOT EXISTS ix_one_time_codes_expires_at ON security.one_time_codes(one_time_code_expires_at);`,

    // User Devices (for 2-step login on new devices)
    `CREATE TABLE IF NOT EXISTS security.user_devices (
        user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES security.users(user_id) ON DELETE CASCADE,
        user_device_token_hash TEXT NOT NULL,
        user_device_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        user_device_last_used_at TIMESTAMPTZ,
        user_device_revoked_at TIMESTAMPTZ,
        user_device_label TEXT,
        user_device_ua TEXT,
        user_device_ip INET,
        user_device_meta JSONB
    );`,
    `CREATE UNIQUE INDEX IF NOT EXISTS uq_user_devices_token ON security.user_devices(user_id, user_device_token_hash);`,
    `CREATE INDEX IF NOT EXISTS ix_user_devices_user_id ON security.user_devices(user_id);`,
]
