name: Bug report
description: Report a reproducible problem
title: 'bug: '
labels: [bug]
body:
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: What happened?
          placeholder: A short description of the bug.
      validations:
          required: true

    - type: textarea
      id: repro
      attributes:
          label: Steps to reproduce
          description: Provide the smallest set of steps to reproduce the issue.
          placeholder: |
              1. ...
              2. ...
              3. ...
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
      validations:
          required: true

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Runtime details help a lot.
          placeholder: |
              - OS:
              - Node:
              - pnpm:
              - Postgres:
      validations:
          required: false

    - type: textarea
      id: logs
      attributes:
          label: Logs / output
          render: shell
          description: Paste relevant logs (redact secrets).
      validations:
          required: false
