/**
 * Authentication Schema
 * Tables for password resets, one-time codes, and user devices.
 */
export const AUTH_SCHEMA = [
    // Password Resets
    `create table if not exists security.password_resets (
        id bigint generated by default as identity primary key,
        user_id bigint not null references security.users(id) on delete cascade,
        token_hash text not null,
        token_sent_to text,
        created_at timestamptz not null default now(),
        expires_at timestamptz not null,
        used_at timestamptz,
        request_ip inet,
        user_agent text,
        attempt_count integer not null default 0,
        meta jsonb
    );`,
    `create unique index if not exists uq_password_resets_token_hash on security.password_resets(token_hash);`,
    `create index if not exists ix_password_resets_user_id on security.password_resets(user_id);`,
    `create index if not exists ix_password_resets_expires_at on security.password_resets(expires_at);`,

    // One-Time Codes (OTP, Email Verification, etc.)
    `create table if not exists security.one_time_codes (
        id bigint generated by default as identity primary key,
        user_id bigint not null references security.users(id) on delete cascade,
        purpose text not null,
        code_hash text not null,
        created_at timestamptz not null default now(),
        expires_at timestamptz not null,
        consumed_at timestamptz,
        attempt_count integer not null default 0,
        meta jsonb
    );`,
    `create index if not exists ix_one_time_codes_user_purpose on security.one_time_codes(user_id, purpose, created_at desc);`,
    `create index if not exists ix_one_time_codes_expires_at on security.one_time_codes(expires_at);`,

    // User Devices (for 2-step login on new devices)
    `create table if not exists security.user_devices (
        id bigint generated by default as identity primary key,
        user_id bigint not null references security.users(id) on delete cascade,
        device_token_hash text not null,
        created_at timestamptz not null default now(),
        last_used_at timestamptz,
        revoked_at timestamptz,
        label text,
        user_agent text,
        ip inet,
        meta jsonb
    );`,
    `create unique index if not exists uq_user_devices_token on security.user_devices(user_id, device_token_hash);`,
    `create index if not exists ix_user_devices_user_id on security.user_devices(user_id);`,
]
