/**
 * Auto-generated schema for security.audit_logs
 * Generated at: 2026-02-20T10:28:05.086Z
 */
export const AUDIT_LOGS_SCHEMA = [
    // Table Definition
    `create table if not exists security.audit_logs (
        id bigint not null,
        request_id text,
        user_id bigint,
        profile_id bigint,
        object_name text,
        method_name text,
        tx integer,
        action text,
        details jsonb,
        created_at timestamp with time zone not null default now()
    );`,

    // Data Seeding
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('1', 'a3dc1c7a-5464-410a-bb8e-e0950b3818bc', '1', '1', NULL, NULL, NULL, 'login', '{"username":"admin"}', '2026-02-08T02:44:31.516Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('2', '4f773a9b-7818-4c8b-9457-f1614f993d7d', '1', '1', NULL, NULL, NULL, 'logout', '{}', '2026-02-08T02:44:46.335Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('3', 'ecaae392-dc41-4ad2-bf22-dce2ace41853', '2', NULL, NULL, NULL, NULL, 'login', '{"username":"eliab"}', '2026-02-19T22:13:12.975Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('4', '9dbecd86-dec7-4faa-8fbe-4fc8fb6e19b6', '2', NULL, NULL, NULL, NULL, 'logout', '{}', '2026-02-19T22:17:27.466Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('5', 'ed2a3f52-1606-46af-8d47-9432be58ee12', '1', '1', NULL, NULL, NULL, 'login', '{"username":"admin"}', '2026-02-19T22:17:29.651Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('6', '0bcfc93f-4088-498c-a4a6-476b36429b87', '1', '1', NULL, NULL, NULL, 'logout', '{}', '2026-02-19T22:24:17.362Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('7', '31299158-5839-497a-9052-dd5e87d14dcd', '1', '1', NULL, NULL, NULL, 'login', '{"username":"admin"}', '2026-02-19T22:24:26.028Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('8', 'b1946d5b-f964-4e4f-b053-755550a57ecb', '2', NULL, NULL, NULL, NULL, 'login', '{"username":"eliab"}', '2026-02-19T22:24:49.563Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('11', '8c5e62b8-90a7-4ca1-b179-d81523c55762', '1', '1', NULL, NULL, NULL, 'login', '{"username":"admin"}', '2026-02-19T22:30:49.604Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('12', 'd10aaacd-cfb3-4b98-b23b-d56a84dedea2', '1', '1', NULL, NULL, NULL, 'login', '{"username":"admin"}', '2026-02-19T22:40:08.329Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('13', '363d6306-49cd-4b6c-b496-9c3226867f0c', '2', NULL, NULL, NULL, NULL, 'login', '{"username":"eliab"}', '2026-02-19T22:40:35.875Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('14', NULL, '1', '1', 'Notification', 'simulate', NULL, 'ACCESS_DENIED', '{}', '2026-02-19T22:40:43.797Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('15', NULL, '1', '1', 'Notification', 'send', NULL, 'ACCESS_DENIED', '{}', '2026-02-19T22:56:30.954Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('16', NULL, '1', '1', 'Notification', 'send', NULL, 'ACCESS_DENIED', '{}', '2026-02-19T22:58:56.635Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('17', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":101}', '2026-02-19T23:01:01.346Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('18', NULL, '1', '1', 'Notification', 'simulate', NULL, 'EXECUTE_SUCCESS', '{"durationMs":5}', '2026-02-19T23:02:53.833Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('19', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-19T23:03:05.448Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('20', NULL, '2', '1', 'Notification', 'broadcast', NULL, 'EXECUTE_SUCCESS', '{"durationMs":11}', '2026-02-19T23:03:34.974Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('21', NULL, '2', '1', 'Notification', 'broadcast', NULL, 'EXECUTE_SUCCESS', '{"durationMs":1}', '2026-02-19T23:03:40.503Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('22', NULL, '1', '1', 'Notification', 'broadcast', NULL, 'EXECUTE_SUCCESS', '{"durationMs":1}', '2026-02-19T23:03:42.472Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('23', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-19T23:03:47.441Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('24', NULL, '2', '1', 'Notification', 'simulate', NULL, 'EXECUTE_SUCCESS', '{"durationMs":1}', '2026-02-19T23:04:50.048Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('25', NULL, '2', '1', 'Notification', 'simulate', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-19T23:05:00.282Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('26', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-19T23:09:21.228Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('27', NULL, '1', '1', 'Notification', 'broadcast', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-19T23:09:50.257Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('28', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-19T23:10:04.776Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('30', '825098ae-84ce-465d-8d6d-2ed01872f5fc', '1', '1', NULL, NULL, NULL, 'login', '{"username":"admin"}', '2026-02-20T01:06:03.796Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('31', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":28}', '2026-02-20T01:06:11.198Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('32', NULL, '1', '1', 'Notification', 'simulate', NULL, 'EXECUTE_SUCCESS', '{"durationMs":2}', '2026-02-20T01:06:17.098Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('33', NULL, '1', '1', 'Notification', 'simulate', NULL, 'EXECUTE_SUCCESS', '{"durationMs":1}', '2026-02-20T01:06:31.253Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('34', NULL, '1', '1', 'Notification', 'simulate', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-20T01:06:43.825Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('35', NULL, '1', '1', 'Notification', 'broadcast', NULL, 'EXECUTE_SUCCESS', '{"durationMs":1}', '2026-02-20T01:07:26.858Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 
    `INSERT INTO security.audit_logs (id, request_id, user_id, profile_id, object_name, method_name, tx, action, details, created_at) VALUES ('36', NULL, '1', '1', 'Notification', 'send', NULL, 'EXECUTE_SUCCESS', '{"durationMs":0}', '2026-02-20T01:07:34.167Z') ON CONFLICT (id) DO UPDATE SET request_id = EXCLUDED.request_id, user_id = EXCLUDED.user_id, profile_id = EXCLUDED.profile_id, object_name = EXCLUDED.object_name, method_name = EXCLUDED.method_name, tx = EXCLUDED.tx, action = EXCLUDED.action, details = EXCLUDED.details, created_at = EXCLUDED.created_at;`, 

    // Indexes
    `CREATE UNIQUE INDEX audit_logs_pkey ON security.audit_logs USING btree (id);`, 
    `CREATE INDEX ix_audit_logs_created_at ON security.audit_logs USING btree (created_at);`, 
    `CREATE INDEX ix_audit_logs_profile_id ON security.audit_logs USING btree (profile_id);`, 
    `CREATE INDEX ix_audit_logs_request_id ON security.audit_logs USING btree (request_id);`, 
    `CREATE INDEX ix_audit_logs_user_id ON security.audit_logs USING btree (user_id);`, 
]
