/**
 * Audit Schema
 * Tables for tracking user actions and system events.
 */
export const AUDIT_SCHEMA = [
    `create table if not exists security.audit_logs (
        id bigint generated by default as identity primary key,
        request_id text,
        user_id bigint references security.users(id),
        profile_id bigint references security.profiles(id),
        object_name text,
        method_name text,
        tx integer,
        action text,
        details jsonb,
        created_at timestamptz not null default now()
    );`,

    `create index if not exists ix_audit_logs_user_id on security.audit_logs(user_id);`,
    `create index if not exists ix_audit_logs_profile_id on security.audit_logs(profile_id);`,
    `create index if not exists ix_audit_logs_created_at on security.audit_logs(created_at);`,
    `create index if not exists ix_audit_logs_request_id on security.audit_logs(request_id);`,
]
