/**
 * Auto-generated data for security.transactions
 * Generated at: 2026-02-20T10:28:05.140Z
 */
export const DATA_TRANSACTIONS_SCHEMA = [
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('27', '1', '27', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('28', '2', '28', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('29', '3', '29', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('30', '4', '30', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('31', '5', '31', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('32', '6', '32', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('33', '7', '33', '1', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('34', '8', '34', '3', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('35', '9', '35', '3', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('36', '10', '36', '3', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('37', '21', '37', '3', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('38', '22', '38', '3', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
    `INSERT INTO security.transactions (transaction_id, transaction_number, method_id, object_id, subsystem_id) VALUES ('39', '23', '39', '3', NULL) ON CONFLICT (transaction_id) DO UPDATE SET transaction_number = EXCLUDED.transaction_number, method_id = EXCLUDED.method_id, object_id = EXCLUDED.object_id, subsystem_id = EXCLUDED.subsystem_id;`,
]
