/**
 * Auto-generated data for business.inventory
 * Generated at: 2026-03-25T22:55:09.747Z
 */
export const DATA_INVENTORY_SCHEMA = [
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (1, 100, '2026-03-25T22:44:48.346Z', 1, 1) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (2, 50, '2026-03-25T22:44:55.853Z', 1, 2) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (3, 30, '2026-03-25T22:45:02.669Z', 2, 3) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (4, 50, '2026-03-25T22:45:11.261Z', 2, 4) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (5, 80, '2026-03-25T22:45:17.108Z', 3, 5) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (6, 50, '2026-03-25T22:45:24.411Z', 3, 6) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (7, 50, '2026-03-25T22:45:43.274Z', 4, 7) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (8, 20, '2026-03-25T22:45:48.267Z', 4, 8) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (9, 50, '2026-03-25T22:46:00.057Z', 5, 9) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (10, 120, '2026-03-25T22:46:12.004Z', 5, 10) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (11, 100, '2026-03-25T22:46:58.185Z', 5, 11) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (12, 1, '2026-03-25T22:47:17.464Z', 6, 12) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (13, 1, '2026-03-25T22:47:22.568Z', 6, 13) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (14, 1, '2026-03-25T22:47:28.760Z', 6, 14) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (15, 1, '2026-03-25T22:47:39.015Z', 7, 15) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (16, 1, '2026-03-25T22:47:40.999Z', 7, 16) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (17, 1, '2026-03-25T22:47:43.182Z', 7, 17) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (18, 1, '2026-03-25T22:48:01.549Z', 8, 18) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (19, 1, '2026-03-25T22:48:05.038Z', 8, 19) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (20, 1, '2026-03-25T22:48:07.310Z', 8, 20) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (21, 1, '2026-03-25T22:48:14.287Z', 8, 21) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (22, 1, '2026-03-25T22:48:25.499Z', 9, 22) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (23, 1, '2026-03-25T22:48:27.683Z', 9, 23) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (24, 1, '2026-03-25T22:48:29.612Z', 9, 24) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
    `INSERT INTO business.inventory (inventory_id, inventory_qt, inventory_updated_dt, location_id, item_id) VALUES (25, 1, '2026-03-25T22:48:31.726Z', 9, 25) ON CONFLICT (inventory_id) DO UPDATE SET inventory_qt = EXCLUDED.inventory_qt, inventory_updated_dt = EXCLUDED.inventory_updated_dt, location_id = EXCLUDED.location_id, item_id = EXCLUDED.item_id;`,
]
